#!/usr/bin/env bash

source etc/banner
# Banner Add
echo -e "executing: ${LIGHTGREEN}—͟͞𝑵 𝑬 𝑯 𝑨™'s ThePAK${NOCOLOR}"
echo "-----------------------"

if [[ -d "output" ]]
  then
    echo ""
  else
    echo ""
    mkdir output
fi

repacking () {
  qemu-i386 $PREFIX/share/quickbms/quickbms -w -r etc/oreo.bms $opt output
}

function repack {
prompt="Please select a file to repack:"
options=( $(find *.pak) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $opt which is file $REPLY"
         repacking
        break
    else
        echo "Invalid option. Try another one."
    fi
done
}

PS3='Please enter your choice: '
options=("Repack" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Repack")
            repack
            
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done 
